### PR TITLE
Add Doctrine Coding standard

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by bpolaszek** [comment]
Please rebase

**Comment by bpolaszek** [comment]
Although I like the idea of reformatting with a coding standard and having it checked in the CI, I'm not fan of Doctrine's one (especially aligning [assignments](https://github.com/bpolaszek/php-iterable-functions/blob/201cd598e1a5cedc8aa02710be0282978f5fb9d7/tests/IterableMapTest.php#L17-L18) and [PHPDoc blocks](https://github.com/bpolaszek/php-iterable-functions/blob/201cd598e1a5cedc8aa02710be0282978f5fb9d7/src/iterable-functions.php#L36-L37), forbidding yoda style, etc). Would you mind just using the PSR-12 standard?

**Comment by simPod** [comment]
@bpolaszek what if we disable assignment aligning? The benefit here is that it's very actively maintained and updated. PSR-12 is still a century behind.

**Comment by bpolaszek** [comment]
If you can disable the 3 rules that bothered me, then go ahead :-)

**Comment by simPod** [comment]
aight, let's see

**Comment by simPod** [comment]
I see no forced alignments now, tried also constants and it's not forced there as well. What about now?

**Review by bpolaszek — APPROVED** [review]
Sounds better 🙂

**Comment by bpolaszek** [comment]
Can you please rebase again?

**Comment by simPod** [comment]
On it. If there are any more problematic rules later, we can always tweak it.

**Comment by simPod** [comment]
> Can you please rebase again?

It's already above v2 branch 🤔

**Comment by bpolaszek** [comment]
My bad, headache doesn't help 😄 
Thx @simPod.

**Pull request merged**
