### PR TITLE
Add iterable_to_generator function

### PR DESCRIPTION
**Pull request by mwijngaard**
Useful for checking if the iterable is empty (valid() will return false) without actually iterating over the iterable.

### CODE REVIEW

**Comment by bpolaszek** [comment]
Hello @mwijngaard,

I actually don't see any use case for this? Can you provide an example?

**Comment by mwijngaard** [comment]
The use case for me is checking whether an iterable (which is possibly forward-only) is empty or not. This is something that the Generator api conveniently exposes in its valid() method. 

e.g.
```
function append_events(string $stream_id, iterable $events): void {
    $gen = iterable_to_generator($events);
    if (!$gen->valid()) {
        return;
    }
    $stream = get_or_create_stream($stream_id);
    foreach ($gen as $event) {
        $stream->append($event);
    }
}
```

In this example I don't want to create the stream if I'm not adding events. The stream creation could be done on the first iteration of the loop of course, but that would reduce the clarity of the code.

**Comment by bpolaszek** [comment]
@mwijngaard I'm sorry, but as this library was intended at first to be a polyfill, I currently prefer to keep compatibility from PHP 5.3+ (your function isn't, _de facto_, because generators cannot exist below PHP 5.5).

Besides, converting an array to a generator is pretty easy since Generators exist in PHP, and more easy since PHP 7's `yield from` syntax, so I don't see the need for that kind of function.

If the only use case of converting an iterable to a generator is to check its non-emptiness, maybe we could create a function like `is_iterable_empty($iterable)`, which could look like this:

```php
# For PHP 5.5+
function is_iterable_empty($iterable)
{
    if (\is_array($iterable)) {
        foreach ($iterable as $value) {
            return false;
        }

        return true;
    }

    if ($iterable instanceof \Generator) {
        return !$iterable->valid();
    }

    if ($iterable instanceof \Countable) {
        return 0 === \count($iterable);
    }

    if ($iterable instanceof \EmptyIterator) {
        return true;
    }

    return !(function ($iterable) {
        foreach ($iterable as $key => $value) {
            yield $key => $value;
        }
    })($iterable)->valid();
}
```


```php
# For PHP 5.3+
function is_iterable_empty($iterable)
{
    if (\is_array($iterable)) {
        foreach ($iterable as $value) {
            return false;
        }

        return true;
    }

    if ($iterable instanceof \Generator) {
        return !$iterable->valid();
    }

    if ($iterable instanceof \Countable) {
        return 0 === \count($iterable);
    }

    if ($iterable instanceof \EmptyIterator) {
        return true;
    }

    return 0 === \iterator_count($iterable);
}
```

What do you think?

**Comment by mwijngaard** [comment]
I can see how that would be more in the spirit of the library. And the beauty is actually that this doesn't require two different implementations. As generators are themselves also Iterators, only the following implementation would be required:

```
function is_iterable_empty($iterable)
{
    if (is_array($iterable)) {
        return empty($iterable);
    }

    if ($iterable instanceof \Iterator) {
        return !$iterable->valid();
    }

    if ($iterable instanceof \IteratorAggregate) {
        return is_iterable_empty($iterable->getIterator());
    }

    if ($iterable instanceof \Countable) {
        return count($iterable) === 0;
    }

    return 0 === \iterator_count($iterable);
}
```

**Comment by bpolaszek** [comment]
Not really: `0 === \iterator_count($iterable)` can be very expensive: if you have a (non-countable) iterator of 2M lines, it will be entirely traversed, so this solution should be avoided as much as possible ; that's why I put it at the very bottom.

When converting the iterator to a generator (when possible) and using the `valid()` method, PHP will only check for the existence of the 1st element, which is a huge performance improvement compared to `iterator_count()`.

**Comment by mwijngaard** [comment]
Isn't that case covered by: 
```
    if ($iterable instanceof \Iterator) {
        return !$iterable->valid();
    }
```

Actually the whole iterator_count line should not be necessary. Or is there another Traversable that is not an array, not an Iterator, and not an IteratorAggregate?

**Comment by bpolaszek** [comment]
To be tested:

```php
function is_iterable_empty($iterable)
{
    if ($iterable instanceof \Iterator) {
        return !$iterable->valid();
    }

}

dump(is_iterable_empty(new IteratorIterator(new class implements IteratorAggregate
{
    public function getIterator()
    {
        yield 'foo';
        yield 'bar';
    }

})));
```

-> gives me `true` :neutral_face:

**Comment by mwijngaard** [comment]
Ok, I'll setup some tests and then submit a new PR.

**Pull request closed without merging**
