### PR TITLE
Add types to iterable_filter()

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Review by bpolaszek — APPROVED** [review]

**Comment by bpolaszek** [comment]
Please rebase

**Comment by bpolaszek** [comment]
Thank you @simPod 🙂

**Comment by simPod** [comment]
We're getting close ;)

**Comment by bpolaszek** [comment]
Yay 🎉  Tell me when you're done with #23, and unless you notice something we missed, I think we'll be ready to tag 2.0.

**Comment by simPod** [comment]
@bpolaszek ~some bugs in IterableObject were found~. Let's continue there.

**Pull request merged**
