### PR TITLE
Drop useless tests as we have types now

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by bpolaszek** [comment]
They have already been dropped in #14.

**Comment by simPod** [comment]
This could be prerequisite for #13 so it's granular. But feel free to close if you wish

**Comment by bpolaszek** [comment]
As #13 is already merged, I'm closing this one if you don't mind :-)

**Comment by simPod** [comment]
@bpolaszek but there's still some diff here after I rebased for check 🤔

**Comment by bpolaszek** [comment]
Anyway, I didn't port obsolete tests on [Pest](https://github.com/bpolaszek/php-iterable-functions/pull/14/files) since we now rely on PHP7 type hinting.

**Comment by simPod** [comment]
Yup, that's correct for sure. but something like `tests/IterableToArrayTest.php` will stay right? So those tests in diff here are redundant and can be dropped

**Pull request closed without merging**
